language: node_js
node_js:
    - "10"
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: compile
      if: branch != main
      script: npm run build
    - stage: deploy
      if: branch = main
      script: npm run build:docs
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs
        github_token: $GITHUB_TOKEN
        on:
          branch: main